sudo: false
language: node_js
node_js:
  - stable # use nodejs v10 LTS
cache: npm

branches:
  only:
    - hexo # build master branch only  # 源代码分支hexo

before_install:
  - export TZ='Asia/Shanghai' # 更改时区

  # - openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d  # 远程登录服务器 

  - openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

script:
  - hexo clean
  - hexo generate # generate static files

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  target_branch: master # 因为Travis默认推送到gh-pages，而我们这里要改推送到master
  fqdn: xyzdy.cn
  on:
    branch: hexo  # 源代码分支hexo
  local_dir: public

after_success:
  - ssh root@39.99.202.209 -o StrictHostKeyChecking=no 'cd /www/wwwroot &&  git pull -b master https://github.com/xiongyizhu/xiongyizhu.github.io.git'